# Download the base image
FROM python:3
# Copy the code from local to docker image
COPY HelloWorld.py .
#Expose the port
EXPOSE 80
# Command to run the program in the shell
CMD [ "python", "./HelloWorld.py"]